#ifndef ACS_PROCESSING_H
#define ACS_PROCESSING_H

typedef enum
{
    PROC_FSM_SIGNAL_HEALTHY,
    PROC_FSM_SIGNAL_A_FAIL,
    PROC_FSM_SIGNAL_B_FAIL,
    PROC_FSM_COMPLEMENTARITY_WAR,
    PROC_FSM_COMPLEMENTARITY_FAIL,
    PROC_FSM_SIGNAL_FAIL
} processing_state_e;

#endif // ACS_PROCESSING_H
